### ISSUE TITLE
Usability suggestion: remove alerts

### ISSUE THREAD

**Issue by jneidel** [Alexever17/alexever17.github.io#1]
Just open the project in a new tab instead of asking for permission via an alert.
It's just annoying and serves no purpose 😄

**Comment by Alexever17** [comment]
Yeah, that makes sense! I actually build it in for the mobile devices, because the area where the projects are showcased is pretty big and it would be more annoying to accidentally click it then to hit one more yes, but it really doesn't make sense for desktop devices

**Comment by Alexever17** [comment]
it is also somehow sad, to disable that now, because it was actually quite complicated to implement haha

**Comment by Alexever17** [comment]
yeah after implementing, i don't understand anymore why i did it in the first place
thanks for the help

issue closed
